# Generated by Django 4.2.7 on 2024-12-19 12:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_permissions_and_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to=accounts.models.user_profile_picture_path),
        ),
    ] 