# Generated by Django 4.2.7 on 2025-05-21 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CALL', 'Call'), ('DEADLINE', 'Deadline'), ('REVIEW', 'Review'), ('OTHER', 'Other')], default='MEETING', max_length=10),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
