# Generated by Django 4.2.7 on 2025-05-21 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sale',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('C', 'Completed'), ('O', 'Overdue')], default='P', max_length=2),
        ),
    ]
